version: '3.8'

db-env-variables: &db-env-variables
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: transactions_history

app-env-variables: &app-env-variables
    <<: *db-env-variables
    POSTGRES_HOST: db

services: 
    app:
        build:
            context: .
            args: *app-env-variables
        volumes:
            - .:/app
        container_name: app
        depends_on:
            - db
        ports: 
            - 8080:8080
        restart: always
    db:
        container_name: postgresdb # app не видит postgres
        image: postgres:13
        ports:
            - 5430:5432
        environment: *db-env-variables
