version: '3.8'

x-db-variables: &db-variables
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: transactions_history

x-app-variables: &app-variables
    <<: *db-variables
    POSTGRES_HOST: db

services: 
    app:
        image: transactions-history:latest
        environment: *app-variables
        volumes:
            - .:/app
        container_name: app
        depends_on:
            - db
        ports: 
            - 8080:8080
        restart: always
        command: bash -c "alembic upgrade head && python run.py --host 0.0.0.0 --port 8080"
    db:
        container_name: postgresdb
        image: postgres:13
        ports:
            - 5432:5432
        environment: *db-variables
