"""changing type from date to datetime

Revision ID: 1ebcf78b8c77
Revises: fe70696850ea
Create Date: 2020-12-01 19:36:14.446024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebcf78b8c77'
down_revision = 'fe70696850ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
