"""daleted foreignkey transcations -> limits

Revision ID: fe70696850ea
Revises: 123ee4b767da
Create Date: 2020-12-01 19:26:40.692804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe70696850ea'
down_revision = '123ee4b767da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transfer_history_limits_id_fkey', 'transfer_history', type_='foreignkey')
    op.drop_column('transfer_history', 'limits_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_history', sa.Column('limits_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('transfer_history_limits_id_fkey', 'transfer_history', 'limits', ['limits_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
